export enum pathENUM {
  about = 'about',
  star = 'star',
  texture = 'texture',
  light = 'light',
  camera = 'camera',
  fake = 'fake',
  shadow = 'shadow',
  shadow2 = 'shadow2',
  fog = 'fog',
  test = 'test',
  target = 'target',
  demand = 'demand',
  HelloCanvas = 'HelloCanvas',
};
